quadrantChart
    title Reach and engagement of campaigns
    x-axis Low Reach --> High Reach
    y-axis Low Engagement --> High Engagement
    quadrant-1 We should expand
    quadrant-2 Need to promote
    quadrant-3 Re-evaluate
    quadrant-4 May be improved
    "ArbiTool": [0.7, 0.4]
    "HaasOnline": [0.6, 0.8]
    "Blackbird Bitcoin Arbitrage": [0.4, 0.3]
    "Gimmer": [0.5, 0.6]
    "Crypto Arbitrage Trader’s source code": [0.3, 0.5]
    "Our Target Product": [0.8, 0.7]
